name: Build and Publish Docker Images

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: auscalabledronecloud/nodeodm,auscalabledronecloud/nodeodm_gpu
        tag-semver: |
          {{version}}
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: |
          ${{ steps.docker_meta.outputs.tags }}
          auscalabledronecloud/nodeodm:latest
    - name: Build and push GPU Docker image
      id: docker_build_gpu
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile.gpu
        push: true
        tags: |
          ${{ steps.docker_meta.outputs.tags }}
          auscalabledronecloud/nodeodm_gpu:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
